"""Pentest report rendering — turns a finished scan into a shareable report.

``render_markdown`` produces a clean Markdown pentest report (severity-grouped,
with evidence, reproduction, remediation, and regression status). ``render_json``
returns a structured dict for programmatic consumers.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from redhive.models import normalize_severity

_SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]
_SEV_EMOJI = {
    "critical": "🟥",
    "high": "🔴",
    "medium": "🟠",
    "low": "🟡",
    "info": "⚪",
}


def _counts(findings: list[dict[str, Any]]) -> dict[str, int]:
    out: dict[str, int] = {}
    for f in findings:
        sev = normalize_severity(f.get("severity"))
        out[sev] = out.get(sev, 0) + 1
    return out


def render_json(scan: dict[str, Any]) -> dict[str, Any]:
    """Structured report payload."""
    findings = scan.get("findings", [])
    return {
        "scan_id": scan.get("scan_id"),
        "target": scan.get("target"),
        "status": scan.get("status"),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": _counts(findings),
        "regression": scan.get("regression_summary"),
        "findings": findings,
        "fixed": scan.get("fixed", []),
    }


def render_markdown(scan: dict[str, Any]) -> str:
    """Human-readable Markdown pentest report."""
    findings = list(scan.get("findings", []))
    counts = _counts(findings)
    target = scan.get("target", "unknown")
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = [
        f"# RedHive Pentest Report",
        "",
        f"**Target:** `{target}`  ",
        f"**Scan ID:** `{scan.get('scan_id', '')}`  ",
        f"**Status:** {scan.get('status', 'unknown')}  ",
        f"**Generated:** {generated}",
        "",
        "## Summary",
        "",
        "| Severity | Count |",
        "| --- | --- |",
    ]
    for sev in _SEVERITY_ORDER:
        if counts.get(sev):
            lines.append(f"| {_SEV_EMOJI[sev]} {sev.title()} | {counts[sev]} |")
    lines.append(f"| **Total** | **{len(findings)}** |")

    reg = scan.get("regression_summary")
    if reg:
        lines += [
            "",
            "## Regression (vs previous scan)",
            "",
            f"- 🆕 New: **{reg.get('new', 0)}**",
            f"- ♻️ Recurring: **{reg.get('recurring', 0)}**",
            f"- ✅ Fixed: **{reg.get('fixed', 0)}**",
        ]

    lines += ["", "## Findings", ""]
    if not findings:
        lines.append("_No findings._")

    # Sort findings high -> low for the report body.
    findings.sort(key=lambda f: _SEVERITY_ORDER.index(normalize_severity(f.get("severity"))))
    for i, f in enumerate(findings, 1):
        sev = normalize_severity(f.get("severity"))
        reg_tag = f" · _{f['regression']}_" if f.get("regression") else ""
        lines += [
            f"### {i}. {_SEV_EMOJI.get(sev, '')} {f.get('title', 'Finding')} "
            f"({sev.upper()}){reg_tag}",
            "",
            f"- **Category:** {f.get('category', '')}",
            f"- **Target:** `{f.get('target', '')}`",
        ]
        if f.get("description"):
            lines.append(f"- **Description:** {f['description']}")
        if f.get("evidence"):
            lines += ["", "**Evidence:**", "", "```", str(f["evidence"]), "```"]
        repro = f.get("reproduction") or []
        if repro:
            lines += ["", "**Reproduction:**", ""]
            lines += [f"{j}. {step}" for j, step in enumerate(repro, 1)]
        if f.get("remediation"):
            lines += ["", f"**Remediation:** {f['remediation']}"]
        lines.append("")

    fixed = scan.get("fixed", [])
    if fixed:
        lines += ["## Fixed since last scan", ""]
        for f in fixed:
            lines.append(f"- ✅ {f.get('title', '')} ({f.get('category', '')})")
        lines.append("")

    lines += ["---", "_Generated by RedHive — authorized practice targets only._"]
    return "\n".join(lines)
